name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # 创建版本号
  increment-version:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && contains(github.event.head_commit.message, 'release'))
    name: Increment Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.NEW_VERSION }}
      body: ${{ steps.create-release.outputs.RELEASE_BODY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Increment version
        id: set-version
        run: |
          VERSION=$(git tag --sort=-v:refname | head -n 1)
          MAJOR=$(echo $VERSION | awk -F. '{print $1}' | sed 's/v//')
          MINOR=$(echo $VERSION | awk -F. '{print $2}')
          PATCH=$(echo $VERSION | awk -F. '{print $3}')
          PATCH=$((PATCH + 1))
          if [ "$PATCH" -gt 9 ]; then
            PATCH=0
            MINOR=$((MINOR + 1))
          fi
          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "::set-output name=NEW_VERSION::$NEW_VERSION"

      - name: Create release body
        id: create-release
        run: |
          # 获取上一个tag
          PREV_TAG=$(git describe --tags --abbrev=0)
          # 获取最后一个tag到现在的所有commit信息
          COMMITS=$(git log ${PREV_TAG}..HEAD --pretty=format:"* %s")
          # 如果没有commit信息，使用默认消息
          if [ -z "$COMMITS" ]; then
            COMMITS="* Regular update and bug fixes"
          fi
          # 创建changelog链接
          CHANGELOG_LINK="https://github.com/${GITHUB_REPOSITORY}/compare/${PREV_TAG}...${{ steps.set-version.outputs.NEW_VERSION }}"
          # 创建release body
          RELEASE_BODY="## What's Changed\n\n${COMMITS}\n\n**Full Changelog**: [${PREV_TAG}...${{ steps.set-version.outputs.NEW_VERSION }}](${CHANGELOG_LINK})"
          # 将release body转义后输出
          echo "RELEASE_BODY<<EOF" >> $GITHUB_OUTPUT
          echo -e "$RELEASE_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set-version.outputs.NEW_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Release ${{ steps.set-version.outputs.NEW_VERSION }}"
          body: ${{ steps.create-release.outputs.RELEASE_BODY }}
          prerelease: false
          draft: false


  build-and-upload:
    name: Build and Upload
    needs: increment-version
    strategy:
      matrix:
        node: [lts/*]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm' # use cache

      - name: Build
        env:
          os: ${{ runner.os == 'Windows' && 'win' || runner.os == 'macOS' && 'macos' || 'linux' }}
        run: |
          npm run install-all
          npm run build
          npm run electron:build:${{ env.os }}

      - name: Rename files - win
        if: runner.os == 'Windows'
        run: |
          mv "./dist_electron/MoeKoe_Music_Setup_${{ needs.increment-version.outputs.version }}.exe" "./MoeKoe_Music_Setup_${{ needs.increment-version.outputs.version }}.exe"
          mv "./dist_electron/MoeKoe_Music_Setup_${{ needs.increment-version.outputs.version }}.exe.blockmap" "./MoeKoe_Music_Setup_${{ needs.increment-version.outputs.version }}.exe.blockmap"
          mv "./dist_electron/latest.yml" "./latest.yml"
      - name: Rename files - mac
        if: runner.os == 'macOS'
        run: |
          mv "./dist_electron/MoeKoe Music-arm64.dmg" "./MoeKoe_Music_${{ needs.increment-version.outputs.version }}-arm64.dmg"
          mv "./dist_electron/MoeKoe Music-x64.dmg" "./MoeKoe_Music_${{ needs.increment-version.outputs.version }}-x64.dmg"
      - name: Rename files - linux
        if: runner.os == 'Linux'
        run: |
          mv "./dist_electron/MoeKoe Music.AppImage" "./MoeKoe_Music_${{ needs.increment-version.outputs.version }}.AppImage"
          mv "./dist_electron/MoeKoe Music.deb" "./MoeKoe_Music_${{ needs.increment-version.outputs.version }}_amd64.deb"

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.increment-version.outputs.version }}
          files: |
            ./MoeKoe_Music_Setup_${{ needs.increment-version.outputs.version }}.exe
            ./MoeKoe_Music_Setup_${{ needs.increment-version.outputs.version }}.exe.blockmap
            ./latest.yml

            ./MoeKoe_Music_${{ needs.increment-version.outputs.version }}-arm64.dmg
            ./MoeKoe_Music_${{ needs.increment-version.outputs.version }}-x64.dmg

            ./MoeKoe_Music_${{ needs.increment-version.outputs.version }}.AppImage
            ./MoeKoe_Music_${{ needs.increment-version.outputs.version }}_amd64.deb
